### ISSUE TITLE
FastAPI + 코드리스

### ISSUE THREAD

**Issue by KarmaPol** [KarmaPol/OME2.0#1]
## FastAPI + Mangum + SAM
https://velog.io/@insutance/simple-deploy-with-fastapi-mangum-lambda-sam

### AWS SAM
- 공식문서
https://docs.aws.amazon.com/ko_kr/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html
```
sam build

sam deploy --guided // 초기 배포

sam sync --stack-name sam-app // 업데이트
```

**Comment by KarmaPol** [comment]
### AWS SAM lambda time out 설정
```
Resources:
  Function: # SAM Local에서 호출하는 함수
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "OmeRestaurantLambda"  # Lambda Function Name
      CodeUri: .  # Lambda Function이 담겨 있는 위치
      Handler: src.main.handler # Lambda Handler 함수의 위치
      Runtime: python3.9
      Timeout: 15 // 기본값 3초
```
